<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Page_model extends CI_Model
{
  public $table = 'page';
  public $id    = 'id_page';

  function get_by_id($id)
  {
    $this->db->where('judul_seo', $id);
    return $this->db->get($this->table)->row();
  }

  // update data
  function update($id, $data)
  {
    $this->db->where($this->id,$id);
    $this->db->update($this->table, $data);
  }

}

/* End of file Komentar_model.php */
/* Location: ./application/models/Komentar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */
